services:
  - type: web
    name: api-catchasync
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: api-cache
          property: connectionString
      - key: DATABASE_URL
        sync: false # Set this in the Render Dashboard -> Environment -> Env Vars

  - type: keyvalue
    name: api-cache
    plan: free
    ipAllowList: [] # Internal access only
